
import numpy as np
import dqabTransforms as tr
import matplotlib.pyplot as plt

# This program plots the alpha beta voltage vectors that can be generated by a 2-level VSC

# Defining the DC side voltage
vDC = 10 

# Defining the possible three phase voltages
voltages = [np.array([[0],[0],[0]]),
            np.array([[0],[0],[vDC]]),
            np.array([[0],[vDC],[0]]),
            np.array([[0],[vDC],[vDC]]),
            np.array([[vDC],[0],[0]]),
            np.array([[vDC],[0],[vDC]]),
            np.array([[vDC],[vDC],[0]]),
            np.array([[vDC],[vDC],[vDC]])]

# Transforming to the alpha beta frame
voltagesAB = []
for v in voltages:
    voltagesAB.append(tr.abc2ab(v))

# Printing results
for i in range(len(voltagesAB)):
    print(f'Case {i+1}: alpha = {float(voltagesAB[i][0])}, beta = {float(voltagesAB[i][1])}')

# Plotting
plt.figure()
for v in voltagesAB:
    plt.plot([0, v[0]],[0, v[1]])
plt.show()


